-- MySQL Script generated by MySQL Workbench
-- sex 16 ago 2019 19:50:44 -03
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`CATEGORIA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CATEGORIA` (
  `idCATEGORIA` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idCATEGORIA`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PAIS`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PAIS` (
  `idPAIS` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`idPAIS`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`REGIAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`REGIAO` (
  `idREGIAO` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `PAIS_idPAIS` INT NOT NULL,
  PRIMARY KEY (`idREGIAO`),
  INDEX `fk_REGIAO_PAIS1_idx` (`PAIS_idPAIS` ASC) VISIBLE,
  CONSTRAINT `fk_REGIAO_PAIS1`
    FOREIGN KEY (`PAIS_idPAIS`)
    REFERENCES `mydb`.`PAIS` (`idPAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PRODUTOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PRODUTOR` (
  `idPRODUTOR` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `REGIAO_idREGIAO` INT NOT NULL,
  PRIMARY KEY (`idPRODUTOR`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  UNIQUE INDEX `telefone_UNIQUE` (`telefone` ASC) VISIBLE,
  INDEX `fk_PRODUTOR_REGIAO1_idx` (`REGIAO_idREGIAO` ASC) VISIBLE,
  CONSTRAINT `fk_PRODUTOR_REGIAO1`
    FOREIGN KEY (`REGIAO_idREGIAO`)
    REFERENCES `mydb`.`REGIAO` (`idREGIAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`ROTULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`ROTULO` (
  `idROTULO` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `descricao` VARCHAR(255) NULL,
  `volume` DECIMAL(5,2) NOT NULL,
  `percentual_alcoolico` DECIMAL(5,2) NOT NULL,
  `preco` DECIMAL(8,2) NOT NULL,
  `ano_producao` INT NOT NULL,
  `CATEGORIA_idCATEGORIA` INT NOT NULL,
  `PRODUTOR_idPRODUTOR` INT NOT NULL,
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  PRIMARY KEY (`idROTULO`),
  INDEX `fk_ROTULO_CATEGORIA_idx` (`CATEGORIA_idCATEGORIA` ASC) VISIBLE,
  INDEX `fk_ROTULO_PRODUTOR1_idx` (`PRODUTOR_idPRODUTOR` ASC) VISIBLE,
  CONSTRAINT `fk_ROTULO_CATEGORIA`
    FOREIGN KEY (`CATEGORIA_idCATEGORIA`)
    REFERENCES `mydb`.`CATEGORIA` (`idCATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_ROTULO_PRODUTOR1`
    FOREIGN KEY (`PRODUTOR_idPRODUTOR`)
    REFERENCES `mydb`.`PRODUTOR` (`idPRODUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VINICOLA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VINICOLA` (
  `PRODUTOR_idPRODUTOR` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `rua` VARCHAR(45) NOT NULL,
  `bairro` VARCHAR(45) NOT NULL,
  `cep` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`PRODUTOR_idPRODUTOR`),
  CONSTRAINT `fk_VINICOLA_PRODUTOR1`
    FOREIGN KEY (`PRODUTOR_idPRODUTOR`)
    REFERENCES `mydb`.`PRODUTOR` (`idPRODUTOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CIDADE` (
  `idCIDADE` INT NOT NULL,
  `nome` VARCHAR(255) NULL,
  `PAIS_idPAIS` INT NOT NULL,
  PRIMARY KEY (`idCIDADE`),
  INDEX `fk_CIDADE_PAIS1_idx` (`PAIS_idPAIS` ASC) VISIBLE,
  CONSTRAINT `fk_CIDADE_PAIS1`
    FOREIGN KEY (`PAIS_idPAIS`)
    REFERENCES `mydb`.`PAIS` (`idPAIS`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOJA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOJA` (
  `idLOJA` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  `CIDADE_idCIDADE` INT NOT NULL,
  PRIMARY KEY (`idLOJA`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC) VISIBLE,
  INDEX `fk_LOJA_CIDADE1_idx` (`CIDADE_idCIDADE` ASC) VISIBLE,
  CONSTRAINT `fk_LOJA_CIDADE1`
    FOREIGN KEY (`CIDADE_idCIDADE`)
    REFERENCES `mydb`.`CIDADE` (`idCIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LOJA-ROTULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`LOJA-ROTULO` (
  `LOJA_idLOJA` INT NOT NULL,
  `ROTULO_idROTULO` INT NOT NULL,
  `quantidade` INT NOT NULL,
  INDEX `fk_INVENTARIO_LOJA1_idx` (`LOJA_idLOJA` ASC) VISIBLE,
  INDEX `fk_INVENTARIO_ROTULO1_idx` (`ROTULO_idROTULO` ASC) VISIBLE,
  PRIMARY KEY (`LOJA_idLOJA`, `ROTULO_idROTULO`),
  CONSTRAINT `fk_INVENTARIO_LOJA1`
    FOREIGN KEY (`LOJA_idLOJA`)
    REFERENCES `mydb`.`LOJA` (`idLOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_INVENTARIO_ROTULO1`
    FOREIGN KEY (`ROTULO_idROTULO`)
    REFERENCES `mydb`.`ROTULO` (`idROTULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DISTRIBUIDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`DISTRIBUIDOR` (
  `idDISTRIBUIDOR` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  PRIMARY KEY (`idDISTRIBUIDOR`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PEDIDO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PEDIDO` (
  `data` DATE NOT NULL,
  `DISTRIBUIDOR_idDISTRIBUIDOR` INT NOT NULL,
  `LOJA_idLOJA` INT NOT NULL,
  `ROTULO_idROTULO` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`data`, `DISTRIBUIDOR_idDISTRIBUIDOR`, `LOJA_idLOJA`, `ROTULO_idROTULO`),
  INDEX `fk_PEDIDO_DISTRIBUIDOR1_idx` (`DISTRIBUIDOR_idDISTRIBUIDOR` ASC) VISIBLE,
  INDEX `fk_PEDIDO_LOJA1_idx` (`LOJA_idLOJA` ASC) VISIBLE,
  INDEX `fk_PEDIDO_ROTULO1_idx` (`ROTULO_idROTULO` ASC) VISIBLE,
  CONSTRAINT `fk_PEDIDO_DISTRIBUIDOR1`
    FOREIGN KEY (`DISTRIBUIDOR_idDISTRIBUIDOR`)
    REFERENCES `mydb`.`DISTRIBUIDOR` (`idDISTRIBUIDOR`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_LOJA1`
    FOREIGN KEY (`LOJA_idLOJA`)
    REFERENCES `mydb`.`LOJA` (`idLOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PEDIDO_ROTULO1`
    FOREIGN KEY (`ROTULO_idROTULO`)
    REFERENCES `mydb`.`ROTULO` (`idROTULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`FUNCIONARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`FUNCIONARIO` (
  `idFUNCIONARIO` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  `ativo` TINYINT NOT NULL,
  `LOJA_idLOJA` INT NOT NULL,
  `idCHEFIA` INT NOT NULL,
  PRIMARY KEY (`idFUNCIONARIO`),
  INDEX `fk_FUNCIONARIO_LOJA1_idx` (`LOJA_idLOJA` ASC) VISIBLE,
  INDEX `fk_FUNCIONARIO_FUNCIONARIO1_idx` (`idCHEFIA` ASC) VISIBLE,
  CONSTRAINT `fk_FUNCIONARIO_LOJA1`
    FOREIGN KEY (`LOJA_idLOJA`)
    REFERENCES `mydb`.`LOJA` (`idLOJA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_FUNCIONARIO_FUNCIONARIO1`
    FOREIGN KEY (`idCHEFIA`)
    REFERENCES `mydb`.`FUNCIONARIO` (`idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`MOTORISTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`MOTORISTA` (
  `CNH` VARCHAR(45) NOT NULL,
  `FUNCIONARIO_idFUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_idFUNCIONARIO`),
  CONSTRAINT `fk_MOTORISTA_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_idFUNCIONARIO`)
    REFERENCES `mydb`.`FUNCIONARIO` (`idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`VENDEDOR`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`VENDEDOR` (
  `comissao` DECIMAL(2,2) NOT NULL,
  `FUNCIONARIO_idFUNCIONARIO` INT NOT NULL,
  PRIMARY KEY (`FUNCIONARIO_idFUNCIONARIO`),
  CONSTRAINT `fk_VENDEDOR_FUNCIONARIO1`
    FOREIGN KEY (`FUNCIONARIO_idFUNCIONARIO`)
    REFERENCES `mydb`.`FUNCIONARIO` (`idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`CLIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`CLIENTE` (
  `idCLIENTE` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `telefone` VARCHAR(45) NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`idCLIENTE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`PROMOCAO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`PROMOCAO` (
  `idPROMOCAO` INT NOT NULL,
  `nome` VARCHAR(255) NOT NULL,
  `data_expiracao` DATETIME NOT NULL,
  `desconto` DECIMAL(2,2) NOT NULL,
  PRIMARY KEY (`idPROMOCAO`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA` (
  `idCOMPRA` VARCHAR(45) NOT NULL,
  `CLIENTE_idCLIENTE` INT NOT NULL,
  `VENDEDOR_FUNCIONARIO_idFUNCIONARIO` INT NOT NULL,
  `data` DATE NOT NULL,
  `PROMOCAO_idPROMOCAO` INT NULL,
  INDEX `fk_COMPRA_CLIENTE1_idx` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  INDEX `fk_COMPRA_VENDEDOR1_idx` (`VENDEDOR_FUNCIONARIO_idFUNCIONARIO` ASC) VISIBLE,
  INDEX `fk_COMPRA_PROMOCAO1_idx` (`PROMOCAO_idPROMOCAO` ASC) VISIBLE,
  UNIQUE INDEX `CLIENTE_idCLIENTE_UNIQUE` (`CLIENTE_idCLIENTE` ASC) VISIBLE,
  UNIQUE INDEX `VENDEDOR_FUNCIONARIO_idFUNCIONARIO_UNIQUE` (`VENDEDOR_FUNCIONARIO_idFUNCIONARIO` ASC) VISIBLE,
  UNIQUE INDEX `data_UNIQUE` (`data` ASC) VISIBLE,
  PRIMARY KEY (`idCOMPRA`),
  CONSTRAINT `fk_COMPRA_CLIENTE1`
    FOREIGN KEY (`CLIENTE_idCLIENTE`)
    REFERENCES `mydb`.`CLIENTE` (`idCLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA_VENDEDOR1`
    FOREIGN KEY (`VENDEDOR_FUNCIONARIO_idFUNCIONARIO`)
    REFERENCES `mydb`.`VENDEDOR` (`FUNCIONARIO_idFUNCIONARIO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA_PROMOCAO1`
    FOREIGN KEY (`PROMOCAO_idPROMOCAO`)
    REFERENCES `mydb`.`PROMOCAO` (`idPROMOCAO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`COMPRA-ROTULO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`COMPRA-ROTULO` (
  `COMPRA_idCOMPRA` VARCHAR(45) NOT NULL,
  `ROTULO_idROTULO` INT NOT NULL,
  `quantidade` INT NOT NULL,
  PRIMARY KEY (`COMPRA_idCOMPRA`, `ROTULO_idROTULO`),
  INDEX `fk_COMPRA-ROTULO_ROTULO1_idx` (`ROTULO_idROTULO` ASC) VISIBLE,
  CONSTRAINT `fk_COMPRA-ROTULO_COMPRA1`
    FOREIGN KEY (`COMPRA_idCOMPRA`)
    REFERENCES `mydb`.`COMPRA` (`idCOMPRA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_COMPRA-ROTULO_ROTULO1`
    FOREIGN KEY (`ROTULO_idROTULO`)
    REFERENCES `mydb`.`ROTULO` (`idROTULO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
